export const AutmationDetailsMock = [
  {
    id: 15,
    name: 'automation-UA',
    description: 'newsletter filtered',
    status: 'Paused',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"510 50\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"770 90\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"1050 250\"},\n{\"key\":\"4\", \"text\":\"Segment those who have opened / clicked email\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Tracking_left.png\", \"name\":\"Tracking\", \"color\":\"white\", \"stroke\":\"#84A4D6\", \"loc\":\"750 250\"},\n{\"key\":\"8\", \"text\":\"Wait for \'n\' number of days / weeks / months\", \"source\":\"/Common/Images/journey/Wait_left.png\", \"name\":\"Wait\", \"color\":\"white\", \"stroke\":\"#66461C\", \"loc\":\"950 510\"},\n{\"key\":\"12\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"950 390\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"1310 570\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[510,75,510,85,585.9999999999999,85,585.9999999999999,33,769.9999999999998,33,769.9999999999998,43]},\n{\"from\":\"1\", \"to\":\"4\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[908,90,918,90,918,170,601.9999999999998,170,601.9999999999998,250,611.9999999999998,250]},\n{\"from\":\"2\", \"to\":\"12\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[1188.0000000000007,250,1198.0000000000007,250,1198.0000000000007,320,801.9999999999993,320,801.9999999999993,390,811.9999999999993,390]},\n{\"from\":\"4\", \"to\":\"2\", \"fromPort\":\"R\", \"toPort\":\"L\", \"visible\":true, \"points\":[887.9999999999998,250,897.9999999999998,250,900.0000000000002,250,900.0000000000002,250,902.0000000000007,250,912.0000000000007,250]},\n{\"from\":\"12\", \"to\":\"8\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[949.9999999999993,437,949.9999999999993,447,949.9999999999993,450.0000000000001,950.0000000000002,450.0000000000001,950.0000000000002,453.00000000000017,950.0000000000002,463.00000000000017]},\n{\"from\":\"8\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[1088.0000000000002,510.00000000000017,1098.0000000000002,510.00000000000017,1309.9999999999998,510.00000000000017,1309.9999999999998,522.5000000000001,1309.9999999999998,535,1309.9999999999998,545]}\n ]}',
    waitEventConfiguration: [
      {
        id: 20,
        journeyEventId: 265,
        numberOfUnits: 2,
        unit: 2,
        key: 8
      }
    ],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [
      {
        id: 25,
        journeyEventId: 264,
        journeyId: 15,
        key: 4,
        name: 'Tracking',
        isConditional: false,
        isNoConditionEvent: false,
        status: 2,
        trackOpenEmail: true,
        trackClickEmail: false
      }
    ],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 14,
        name: 'filter test',
        description: 'Filter created in automation',
        defaultValue: null,
        booleanQuery: 'Gender = \"male\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: '(Gender==\"male\")',
        booleanQueryAsLinq: 'string.Compare(Gender,  \"male\", true) == 0',
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:34:19.6503475Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:34:19.5722132Z',
    creatorUserId: null
  },
  {
    id: 60,
    name: 'welcome email ua',
    description: 'welcome email ua',
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"150 130\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"430 190\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"770 270\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"1070 410\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"5\", \"to\":\"1\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[430,237,430,247,430,270,526,270,622,270,632,270]},\n{\"from\":\"1\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[770,317,770,327,770,351,1070,351,1070,375,1070,385]},\n{\"from\":\"0\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[150,155,150,165,150,190,216,190,282,190,292,190]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 40,
        journeyEventId: 506,
        listId: 121,
        listName: 'New Subscriber Welcome',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:54:19.1291379Z',
    creatorUserId: null
  },
  {
    id: 56,
    name: 'Test 17 April UA',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"30 70\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"310 130\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"210 290\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"490 290\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[30,95,30,105,30,130,96,130,162,130,172,130]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"B\", \"toPort\":\"R\", \"points\":[310,177,310,187,310,211,358,211,358,290,348,290]},\n{\"from\":\"1\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[210,337,210,347,404,347,404,255,490,255,490,265]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 37,
        name: 'City Address',
        description: 'Filter created in automation',
        defaultValue: null,
        // tslint:disable-next-line:max-line-length
        booleanQuery: 'PersonalAddressCity = \"Bangalore\" OR PersonalAddressCity = \"Delhi\" OR PersonalAddressCity = \"Kolkata\" OR (Record.EmailAddress = \"uarora@campaigntocash.com\")',
        defaultFilterName: null,
        defaultFilterId: 0,
        // tslint:disable-next-line:max-line-length
        booleanQueryAsString: '(PersonalAddressCity==\"Bangalore\"||PersonalAddressCity==\"Delhi\"||PersonalAddressCity==\"Kolkata\"||(Record.EmailAddress==\"uarora@campaigntocash.com\"))',
        // tslint:disable-next-line:max-line-length
        booleanQueryAsLinq: 'string.Compare(PersonalAddressCity,  \"Bangalore\", true) == 0 OR string.Compare(PersonalAddressCity,  \"Delhi\", true) == 0 OR string.Compare(PersonalAddressCity,  \"Kolkata\", true) == 0 OR (string.Compare(Record.EmailAddress,  \"uarora@campaigntocash.com\", true) == 0)',
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:55:00.782436Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:55:00.7337345Z',
    creatorUserId: null
  },
  {
    id: 55,
    name: 'Testing 17 2020',
    description: null,
    status: 'Paused',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"30 10\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"270 30\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"630 70\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"170 250\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[30,35,30,45,95,45,95,30,122,30,132,30]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[408,30,418,30,450,30,450,70,482,70,492,70]},\n{\"from\":\"1\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[630,117,630,127,630,171,170,171,170,215,170,225]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 36,
        name: 'New 1234',
        description: 'Filter created in automation',
        defaultValue: null,
        booleanQuery: 'Record.EmailAddress = \"prasad.undale@waiin.com\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: '(Record.EmailAddress==\"prasad.undale@waiin.com\")',
        booleanQueryAsLinq: 'string.Compare(Record.EmailAddress,  \"prasad.undale@waiin.com\", true) == 0',
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:55:33.0854222Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:55:33.0426244Z',
    creatorUserId: null
  },
  {
    id: 52,
    name: 'Demo Automation',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"50 30\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"350 30\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"710 50\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"610 210\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[50,55,50,65,145,65,145,30,202,30,212,30]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[488,30,498,30,530,30,530,50,562,50,572,50]},\n{\"from\":\"1\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[848,50,858,50,858,140,610,140,610,175,610,185]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 31,
        name: null,
        description: null,
        defaultValue: null,
        booleanQuery: null,
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: null,
        booleanQueryAsLinq: null,
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:56:07.5242118Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:56:07.4753213Z',
    creatorUserId: null
  },
  {
    id: 51,
    name: 'GO Air Demo',
    description: null,
    status: 'Paused',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"90 50\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"330 70\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"670 110\"},\n{\"key\":\"4\", \"text\":\"Segment those who have opened / clicked email\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Tracking_left.png\", \"name\":\"Tracking\", \"color\":\"white\", \"stroke\":\"#84A4D6\", \"loc\":\"670 250\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"330 250\"},\n{\"key\":\"52\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"510 410\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"870 570\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[90,75,90,85,155,85,155,70,182,70,192,70]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[468,70,478,70,500,70,500,110,522,110,532,110]},\n{\"from\":\"1\", \"to\":\"4\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[670,157,670,167,670,180,670,180,670,193,670,203]},\n{\"from\":\"4\", \"to\":\"5\", \"fromPort\":\"L\", \"toPort\":\"R\", \"visible\":true, \"points\":[532,250,522,250,500,250,500,249.99999999999977,478,249.99999999999977,468,249.99999999999977]},\n{\"from\":\"4\", \"to\":\"52\", \"fromPort\":\"B\", \"toPort\":\"R\", \"visible\":true, \"points\":[670,297,670,307,670,410.00000000000017,664,410.00000000000017,658.0000000000001,410.00000000000017,648.0000000000001,410.00000000000017], \"text\":\"No\"},\n{\"from\":\"5\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[330,296.9999999999998,330,306.9999999999998,330,523.5974910288744,870,523.5974910288744,870,534.9999999999998,870,544.9999999999998]},\n{\"from\":\"52\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[510.0000000000001,457.00000000000017,510.0000000000001,467.00000000000017,510.0000000000001,501,870,501,870,534.9999999999998,870,544.9999999999998]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 38,
        journeyEventId: 466,
        listId: 87,
        listName: 'GO Air Link Click',
        key: 5
      },
      {
        id: 39,
        journeyEventId: 467,
        listId: 88,
        listName: 'Go Air Link not click',
        key: 52
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [
      {
        id: 31,
        journeyEventId: 465,
        journeyId: 51,
        key: 4,
        name: 'Tracking',
        isConditional: false,
        isNoConditionEvent: false,
        status: 0,
        trackOpenEmail: false,
        trackClickEmail: true
      }
    ],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 30,
        name: 'Go Air-basis on income and office',
        description: 'Potential leads for business class',
        defaultValue: null,
        booleanQuery: 'NumericField1 = \"3000000\" OR CorporateAddressCity = \"Bangalore\" OR Company = \"Thoughtworks\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        // tslint:disable-next-line:max-line-length
        booleanQueryAsString: '(NumericField1==\"3000000\"||CorporateAddressCity==\"Bangalore\"||Company==\"Thoughtworks\")',
        // tslint:disable-next-line:max-line-length
        booleanQueryAsLinq: 'NumericField1 == 3000000 OR string.Compare(CorporateAddressCity,  \"Bangalore\", true) == 0 OR string.Compare(Company,  \"Thoughtworks\", true) == 0',
        folderId: 0,
        isExistingFilter: true,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:56:25.1612653Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:56:25.1308171Z',
    creatorUserId: null
  },
  {
    id: 33,
    name: 'Update Field',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"110 50\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"370 70\"},\n{\"key\":\"9\", \"text\":\"Update field of records based on activity\", \"source\":\"/Common/Images/journey/Update_Field_left.png\", \"name\":\"Update Field\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"730 70\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"750 210\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[110,75,110,85,185,85,185,70,222,70,232,70]},\n{\"from\":\"2\", \"to\":\"9\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[508,70,518,70,550,70,550,70,582,70,592,70]},\n{\"from\":\"9\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[730,117,730,127,730,151,750,151,750,175,750,185]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 25,
        name: null,
        description: null,
        defaultValue: null,
        booleanQuery: null,
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: null,
        booleanQueryAsLinq: null,
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:57:05.0999147Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [
      {
        id: 4,
        journeyEventId: 376,
        fieldName: 'LeadOwner',
        fieldValue: 'Manoj',
        key: 9
      }
    ],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:57:05.068461Z',
    creatorUserId: null
  },
  {
    id: 50,
    name: 'Test Demo',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"70 30\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"350 50\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"690 50\"},\n{\"key\":\"4\", \"text\":\"Segment those who have opened / clicked email\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Tracking_left.png\", \"name\":\"Tracking\", \"color\":\"white\", \"stroke\":\"#84A4D6\", \"loc\":\"230 370\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"590 210\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"890 210\"},\n{\"key\":\"8\", \"text\":\"Wait for \'n\' number of days / weeks / months\", \"source\":\"/Common/Images/journey/Wait_left.png\", \"name\":\"Wait\", \"color\":\"white\", \"stroke\":\"#66461C\", \"loc\":\"230 230\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[70,55,70,65,155,65,155,50,202,50,212,50]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[350,97,350,107,519,107,519,50,542,50,552,50]},\n{\"from\":\"4\", \"to\":\"5\", \"fromPort\":\"R\", \"toPort\":\"L\", \"visible\":true, \"points\":[368,370,378,370,410,370,410,210,442,210,452,210]},\n{\"from\":\"5\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[728,210,738,210,795,210,795,175,890,175,890,185]},\n{\"from\":\"1\", \"to\":\"8\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[828,50,838,50,838,139,230,139,230,173,230,183]},\n{\"from\":\"8\", \"to\":\"4\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[230,277,230,287,230,300,230,300,230,313,230,323]}\n ]}',
    waitEventConfiguration: [
      {
        id: 24,
        journeyEventId: 450,
        numberOfUnits: 2,
        unit: 4,
        key: 8
      }
    ],
    addToListEventConfiguration: [
      {
        id: 35,
        journeyEventId: 448,
        listId: 85,
        listName: 'Uspheria Campaign tracking list',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [
      {
        id: 29,
        journeyEventId: 447,
        journeyId: 50,
        key: 4,
        name: 'Tracking',
        isConditional: false,
        isNoConditionEvent: false,
        status: 2,
        trackOpenEmail: false,
        trackClickEmail: true
      }
    ],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 29,
        name: null,
        description: null,
        defaultValue: null,
        booleanQuery: null,
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: null,
        booleanQueryAsLinq: null,
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:57:28.3476237Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:57:28.3181923Z',
    creatorUserId: null
  },
  {
    id: 48,
    name: '7 May During',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"110 10\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"370 30\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"690 90\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[110,35,110,45,185,45,185,30,222,30,232,30]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[508,30,518,30,690,30,690,42.5,690,55,690,65]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:57:53.6758266Z',
    creatorUserId: null
  },
  {
    id: 47,
    name: 'PreEvent7may',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"150 90\"},\n{\"key\":\"10\", \"text\":\"Events activity\", \"source\":\"/Common/Images/journey/Events.png\", \"name\":\"Event\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"350 190\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"690 210\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[150,115,150,125,150,190,176,190,202,190,212,190]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[488,190,498,190,575,190,575,175,690,175,690,185]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:58:14.9525612Z',
    creatorUserId: null
  },
  {
    id: 46,
    name: 'DuringEventTest',
    description: null,
    status: 'Active',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"110 110\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"290 230\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"610 330\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[110,135,110,145,110,230,126,230,142,230,152,230]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[428,230,438,230,610,230,610,262.5,610,295,610,305]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:58:43.3785569Z',
    creatorUserId: null
  },
  {
    id: 44,
    name: 'duringevent',
    description: null,
    status: 'Paused',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"110 30\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"290 130\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"550 130\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[110,55,110,65,110,130,126,130,142,130,152,130]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[428,130,438,130,475,130,475,95,550,95,550,105]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:59:03.5776008Z',
    creatorUserId: null
  },
  {
    id: 40,
    name: 'During11',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"130 90\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"330 210\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"550 330\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"790 350\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[130,115,130,125,130,210,156,210,182,210,192,210]},\n{\"from\":\"5\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[330,257,330,267,330,330,366,330,402,330,412,330]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[688,330,698,330,725,330,725,315,790,315,790,325]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 34,
        journeyEventId: 403,
        listId: 58,
        listName: null,
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:59:26.0710288Z',
    creatorUserId: null
  },
  {
    id: 31,
    name: 'Demo',
    description: null,
    status: 'Failed',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"190 70\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"390 70\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"750 70\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"830 170\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[190,95,190,105,235,105,235,70,242,70,252,70]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[528,70,538,70,570,70,570,70,602,70,612,70]},\n{\"from\":\"1\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[750,117,750,127,750,131,830,131,830,135,830,145]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 24,
        name: null,
        description: null,
        defaultValue: null,
        booleanQuery: null,
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: null,
        booleanQueryAsLinq: null,
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T14:59:46.6086441Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T14:59:46.5616865Z',
    creatorUserId: null
  },
  {
    id: 32,
    name: 'Raw Office Survey',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"90 30\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"350 50\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"830 30\"},\n{\"key\":\"8\", \"text\":\"Wait for \'n\' number of days / weeks / months\", \"source\":\"/Common/Images/journey/Wait_left.png\", \"name\":\"Wait\", \"color\":\"white\", \"stroke\":\"#66461C\", \"loc\":\"870 210\"},\n{\"key\":\"4\", \"text\":\"Segment those who have opened / clicked email\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Tracking_left.png\", \"name\":\"Tracking\", \"color\":\"white\", \"stroke\":\"#84A4D6\", \"loc\":\"930 330\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"230 430\"},\n{\"key\":\"52\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"910 470\"},\n{\"key\":\"12\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"630 590\"},\n{\"key\":\"13\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"250 310\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"550 330\"},\n{\"key\":\"3\", \"text\":\"Segment records based on conditions\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Decision_left.png\", \"name\":\"Decision\", \"color\":\"white\", \"stroke\":\"#00AEEF\", \"loc\":\"210 210\"},\n{\"key\":\"53\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"590 150\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[90,55,90,65,165,65,165,50,202,50,212,50]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[488,50,498,50,590,50,590,29.999999999999957,682.0000000000001,29.999999999999957,692.0000000000001,29.999999999999957]},\n{\"from\":\"1\", \"to\":\"8\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[830.0000000000001,76.99999999999996,830.0000000000001,86.99999999999996,830.0000000000001,119.99999999999997,870,119.99999999999997,870,153,870,163]},\n{\"from\":\"8\", \"to\":\"4\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[870,257,870,267,870,270.0000000000001,929.9999999999998,270.0000000000001,929.9999999999998,273.00000000000017,929.9999999999998,283.00000000000017]},\n{\"from\":\"4\", \"to\":\"5\", \"fromPort\":\"L\", \"toPort\":\"R\", \"visible\":true, \"points\":[791.9999999999998,330.00000000000017,781.9999999999998,330.00000000000017,780,330.00000000000017,780,330.00000000000017,764,330.00000000000017,764,430,378.00000000000006,430,368.00000000000006,430]},\n{\"from\":\"4\", \"to\":\"52\", \"fromPort\":\"R\", \"toPort\":\"L\", \"visible\":true, \"points\":[1067.9999999999998,330.00000000000017,1077.9999999999998,330.00000000000017,1077.9999999999998,400.0000000000002,762.0000000000003,400.0000000000002,762.0000000000003,470.0000000000002,772.0000000000003,470.0000000000002], \"text\":\"No\"},\n{\"from\":\"52\", \"to\":\"12\", \"fromPort\":\"B\", \"toPort\":\"R\", \"points\":[910.0000000000003,517.0000000000002,910.0000000000003,527.0000000000002,910.0000000000003,590,844.0000000000002,590,778,590,768,590]},\n{\"from\":\"5\", \"to\":\"13\", \"fromPort\":\"L\", \"toPort\":\"L\", \"points\":[92.00000000000006,430,82.00000000000006,430,82.00000000000006,310,92.00000000000006,310,102.00000000000006,310,112.00000000000006,310]},\n{\"from\":\"12\", \"to\":\"-1\", \"fromPort\":\"L\", \"toPort\":\"T\", \"points\":[492,590,482,590,482,295,516,295,550,295,550,305]},\n{\"from\":\"13\", \"to\":\"3\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[250.00000000000006,357,250.00000000000006,367,250.00000000000006,367,396,367,396,156,210.00000000000006,156,210.00000000000006,152.99999999999994,210.00000000000006,162.99999999999994]},\n{\"from\":\"3\", \"to\":\"53\", \"fromPort\":\"R\", \"toPort\":\"L\", \"visible\":true, \"points\":[348.00000000000006,209.99999999999994,358.00000000000006,209.99999999999994,426.75,209.99999999999994,426.75,150,442,150,452,150]},\n{\"from\":\"53\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[590,197,590,207,590,251,550,251,550,295,550,305]}\n ]}',
    waitEventConfiguration: [
      {
        id: 23,
        journeyEventId: 365,
        numberOfUnits: 2,
        unit: 1,
        key: 8
      }
    ],
    addToListEventConfiguration: [
      {
        id: 27,
        journeyEventId: 367,
        listId: 56,
        listName: 'List for Survey',
        key: 5
      },
      {
        id: 28,
        journeyEventId: 368,
        listId: 55,
        listName: 'List for Newsletters',
        key: 52
      }
    ],
    decisionEventConfiguration: [
      {
        id: 4,
        journeyEventId: 372,
        booleanQuery: 'Gender = \"Female\"',
        key: 3,
        booleanQueryAsString: '(Gender==\"Female\")',
        booleanQueryAsLinq: 'string.Compare(Gender,  \"Female\", true) == 0',
        noBooleanQuery: 'Gender = \"Male\"',
        noBooleanQueryAsString: 'Gender==\"Male\"',
        noBooleanQueryAsLinq: 'string.Compare(Gender,  \"Male\", true) == 0'
      }
    ],
    filter: null,
    trackingEventConfiguration: [
      {
        id: 28,
        journeyEventId: 366,
        journeyId: 32,
        key: 4,
        name: 'Tracking',
        isConditional: false,
        isNoConditionEvent: false,
        status: 0,
        trackOpenEmail: true,
        trackClickEmail: false
      }
    ],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 20,
        name: 'BASIS ON LOCATION AND REQUIREMENT',
        description: 'FILTER  FOR SORTING TYPE OF ORGANIZATION',
        defaultValue: null,
        // tslint:disable-next-line:max-line-length
        booleanQuery: 'NumberOfEmployees > \"1500\" OR AnnualRevenue >= \"50000\" OR CorporateAddressCountry = \"CANADA\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        // tslint:disable-next-line:max-line-length
        booleanQueryAsString: '(NumberOfEmployees>\"1500\"||AnnualRevenue>=\"50000\"||CorporateAddressCountry==\"CANADA\")',
        // tslint:disable-next-line:max-line-length
        booleanQueryAsLinq: 'NumberOfEmployees greater than 1500 OR AnnualRevenue greater than or equal to 50000 OR string.Compare(CorporateAddressCountry,  \"CANADA\", true) == 0',
        folderId: 0,
        isExistingFilter: true,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T15:00:14.6795212Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:00:14.6168347Z',
    creatorUserId: null
  },
  {
    id: 43,
    name: 'PreTest',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"110 50\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"270 170\"},\n{\"key\":\"10\", \"text\":\"Events activity\", \"source\":\"/Common/Images/journey/Events.png\", \"name\":\"Event\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"530 290\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"810 270\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[110,75,110,85,110,170,116,170,122,170,132,170]},\n{\"from\":\"2\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[270,217,270,227,270,290,326,290,382,290,392,290]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[668,290,678,290,725,290,725,235,810,235,810,245]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 18,
        name: null,
        description: null,
        defaultValue: null,
        booleanQuery: null,
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: null,
        booleanQueryAsLinq: null,
        folderId: 0,
        isExistingFilter: true,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T15:00:36.6383364Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:00:36.604931Z',
    creatorUserId: null
  },
  {
    id: 34,
    name: '11 april',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"70 50\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"310 50\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"630 50\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"890 30\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[70,75,70,85,135,85,135,50,162,50,172,50]},\n{\"from\":\"2\", \"to\":\"10\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[448,50,458,50,470,50,470,50,482,50,492,50]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[768,50,778,50,815,50,815,-5,890,-5,890,5]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 20,
        name: 'BASIS ON LOCATION AND REQUIREMENT',
        description: 'FILTER  FOR SORTING TYPE OF ORGANIZATION',
        defaultValue: null,
        // tslint:disable-next-line:max-line-length
        booleanQuery: 'NumberOfEmployees > \"1500\" OR AnnualRevenue >= \"50000\" OR CorporateAddressCountry = \"CANADA\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        // tslint:disable-next-line:max-line-length
        booleanQueryAsString: '(NumberOfEmployees>\"1500\"||AnnualRevenue>=\"50000\"||CorporateAddressCountry==\"CANADA\")',
        // tslint:disable-next-line:max-line-length
        booleanQueryAsLinq: 'NumberOfEmployees greater than 1500 OR AnnualRevenue greater than or equal to 50000 OR string.Compare(CorporateAddressCountry,  \"CANADA\", true) == 0',
        folderId: 0,
        isExistingFilter: true,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T15:01:00.541299Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:01:00.4944232Z',
    creatorUserId: null
  },
  {
    id: 35,
    name: 'PreTestAutomaiton',
    description: null,
    status: 'InActive',
    lastModificationTime: null,

    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"90 30\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"270 150\"},\n{\"key\":\"10\", \"text\":\"Events activity\", \"source\":\"/Common/Images/journey/Events.png\", \"name\":\"Event\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"470 310\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"750 290\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[90,55,90,65,90,150,106,150,122,150,132,150]},\n{\"from\":\"5\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[270,197,270,207,270,310,296,310,322,310,332,310]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[608,310,618,310,665,310,665,255,750,255,750,265]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 29,
        journeyEventId: 383,
        listId: 60,
        listName: 'SMS Demo',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:01:22.3787613Z',
    creatorUserId: null
  },
  {
    id: 36,
    name: 'DuringEventAutomation',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"90 50\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"330 110\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"510 330\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"790 250\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[90,75,90,85,90,110,136,110,182,110,192,110]},\n{\"from\":\"5\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[330,157,330,167,330,330,346,330,362,330,372,330]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[648,330,658,330,705,330,705,215,790,215,790,225]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 30,
        journeyEventId: 387,
        listId: 59,
        listName: 'Demo List',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:01:43.2159992Z',
    creatorUserId: null
  },
  {
    id: 37,
    name: 'PostEventTest',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"130 70\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"390 170\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"710 230\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"930 250\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[130,95,130,105,130,170,186,170,242,170,252,170]},\n{\"from\":\"5\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[390,217,390,227,390,230,476,230,562,230,572,230]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[848,230,858,230,875,230,875,215,930,215,930,225]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 31,
        journeyEventId: 391,
        listId: 60,
        listName: 'SMS Demo',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:02:13.3856106Z',
    creatorUserId: null
  },
  {
    id: 38,
    name: 'Pre11',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"130 150\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"290 270\"},\n{\"key\":\"10\", \"text\":\"Events activity\", \"source\":\"/Common/Images/journey/Events.png\", \"name\":\"Event\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"410 410\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"690 230\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[130,175,130,185,130,270,136,270,142,270,152,270]},\n{\"from\":\"5\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[290,317,290,327,290,341,262,341,262,410,272,410]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[548,410,558,410,605,410,605,195,690,195,690,205]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 32,
        journeyEventId: 395,
        listId: 59,
        listName: 'Demo List',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:02:36.1796077Z',
    creatorUserId: null
  },
  {
    id: 39,
    name: 'post11',
    description: 'post11',
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"130 70\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"330 150\"},\n{\"name\":\"DuringEvent\", \"key\":\"10\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"color\":\"white\", \"stroke\":\"#5FB292\", \"loc\":\"610 250\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"870 210\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[130,95,130,105,130,150,156,150,182,150,192,150]},\n{\"from\":\"5\", \"to\":\"10\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[330,197,330,207,330,250,396,250,462,250,472,250]},\n{\"from\":\"10\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[748,250,758,250,795,250,795,175,870,175,870,185]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 33,
        journeyEventId: 399,
        listId: 60,
        listName: 'SMS Demo',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:02:57.336476Z',
    creatorUserId: null
  },
  {
    id: 53,
    name: '1',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"170 130\"},\n{\"key\":\"1\", \"text\":\"Send sms to selected list / filters\", \"source\":\"/Common/Images/journey/Sms_Event.png\", \"name\":\"SMS\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"470 210\"},\n{\"key\":\"4\", \"text\":\"Segment those who have sent / not sent sms\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Tracking_left.png\", \"name\":\"SMSTracking\", \"color\":\"white\", \"stroke\":\"#84A4D6\", \"loc\":\"1050 490\"},\n{\"key\":\"3\", \"text\":\"Segment records based on conditions\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Decision_left.png\", \"name\":\"Decision\", \"color\":\"white\", \"stroke\":\"#00AEEF\", \"loc\":\"1050 630\"},\n{\"key\":\"8\", \"text\":\"Wait for \'n\' number of days / weeks / months\", \"source\":\"/Common/Images/journey/Wait_left.png\", \"name\":\"Wait\", \"color\":\"white\", \"stroke\":\"#66461C\", \"loc\":\"750 490\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"1290 670\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"1\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[170,155,170,165,170,210,246,210,322,210,332,210]},\n{\"from\":\"1\", \"to\":\"8\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[608,210,618,210,750,210,750,321.5,750,433,750,443]},\n{\"from\":\"8\", \"to\":\"4\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[888,490,898,490,900,490,900,490,902,490,912,490]},\n{\"from\":\"4\", \"to\":\"3\", \"fromPort\":\"B\", \"toPort\":\"T\", \"visible\":true, \"points\":[1050,537,1050,547,1050,556.8045856876898,1050,556.8045856876898,1050,573,1050,583], \"text\":\"ppppppppppppppp\"},\n{\"from\":\"3\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"visible\":true, \"points\":[1188,630,1198,630,1290,630,1290,632.5,1290,635,1290,645]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:03:25.3768197Z',
    creatorUserId: null
  },
  {
    id: 54,
    name: 'Test Demo123',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"30 30\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"290 50\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"670 50\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"910 170\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[30,55,30,65,106,65,106,-7,290,-7,290,3]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[428,50,438,50,480,50,480,50,522,50,532,50]},\n{\"from\":\"1\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"points\":[808,50,818,50,910,50,910,92.5,910,135,910,145]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 34,
        name: 'Record',
        description: 'Filter created in automation',
        defaultValue: null,
        booleanQuery: 'RecordType = \"Lead\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        booleanQueryAsString: '(RecordType==\"Lead\")',
        booleanQueryAsLinq: 'string.Compare(RecordType,  \"Lead\", true) == 0',
        folderId: 0,
        isExistingFilter: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T15:04:08.4675802Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:04:08.4363567Z',
    creatorUserId: null
  },
  {
    id: 58,
    name: 'Spring Summer Collection',
    description: 'An email campaign for spring summer collection',
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"1450 90\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"1250 270\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"1770 290\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"1790 450\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[1450,115,1450,125,1450,169,1250,169,1250,213,1250,223]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[1388,270,1398,270,1510,270,1510,290,1622,290,1632,290]},\n{\"from\":\"1\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[1770,337,1770,347,1770,381,1790,381,1790,415,1790,425]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 38,
        name: 'Email Campaign for Spring Summer Collection',
        description: null,
        defaultValue: null,
        // tslint:disable-next-line:max-line-length
        booleanQuery: 'BillingAddressState = \"Delhi\" OR BillingAddressState = \"Karnataka\" OR BillingAddressState = \"West Bengal\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        // tslint:disable-next-line:max-line-length
        booleanQueryAsString: '(BillingAddressState==\"Delhi\"||BillingAddressState==\"Karnataka\"||BillingAddressState==\"West Bengal\")',
        // tslint:disable-next-line:max-line-length
        booleanQueryAsLinq: 'string.Compare(BillingAddressState,  \"Delhi\", true) == 0 OR string.Compare(BillingAddressState,  \"Karnataka\", true) == 0 OR string.Compare(BillingAddressState,  \"West Bengal\", true) == 0',
        folderId: 0,
        isExistingFilter: true,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T15:04:34.5667966Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:04:34.5200121Z',
    creatorUserId: null
  },
  {
    id: 59,
    name: 'Demo Automation Sample',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"510 310\"},\n{\"key\":\"2\", \"text\":\"Filter records based on conditions\", \"source\":\"/Common/Images/journey/Filter_left.png\", \"name\":\"Filter\", \"color\":\"white\", \"stroke\":\"#EE2465\", \"loc\":\"390 610\"},\n{\"key\":\"1\", \"text\":\"Send sms to selected list / filters\", \"source\":\"/Common/Images/journey/Sms_Event.png\", \"name\":\"SMS\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"810 610\"},\n{\"key\":\"4\", \"text\":\"Segment those who have sent / not sent sms\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Tracking_left.png\", \"name\":\"SMSTracking\", \"color\":\"white\", \"stroke\":\"#84A4D6\", \"loc\":\"830 790\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"1130 750\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"2\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[510,335,510,345,510,449,390,449,390,553,390,563]},\n{\"from\":\"2\", \"to\":\"1\", \"fromPort\":\"R\", \"toPort\":\"L\", \"points\":[528,610,538,610,600,610,600,610,662,610,672,610]},\n{\"from\":\"1\", \"to\":\"4\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[810,657,810,667,810,700,830,700,830,733,830,743]},\n{\"from\":\"4\", \"to\":\"-1\", \"fromPort\":\"R\", \"toPort\":\"T\", \"visible\":true, \"points\":[968,790,978,790,1035,790,1035,715,1130,715,1130,725]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [
      {
        id: 33,
        journeyEventId: 503,
        journeyId: 59,
        key: 4,
        name: 'SMSTracking',
        isConditional: false,
        isNoConditionEvent: false,
        status: 0,
        trackOpenEmail: false,
        trackClickEmail: false
      }
    ],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [
      {
        key: 2,
        tenantId: null,
        id: 38,
        name: 'Email Campaign for Spring Summer Collection',
        description: null,
        defaultValue: null,
        // tslint:disable-next-line:max-line-length
        booleanQuery: 'BillingAddressState = \"Delhi\" OR BillingAddressState = \"Karnataka\" OR BillingAddressState = \"West Bengal\"',
        defaultFilterName: null,
        defaultFilterId: 0,
        // tslint:disable-next-line:max-line-length
        booleanQueryAsString: '(BillingAddressState==\"Delhi\"||BillingAddressState==\"Karnataka\"||BillingAddressState==\"West Bengal\")',
        // tslint:disable-next-line:max-line-length
        booleanQueryAsLinq: 'string.Compare(BillingAddressState,  \"Delhi\", true) == 0 OR string.Compare(BillingAddressState,  \"Karnataka\", true) == 0 OR string.Compare(BillingAddressState,  \"West Bengal\", true) == 0',
        folderId: 0,
        isExistingFilter: true,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-26T15:04:55.1384864Z',
        creatorUserId: null
      }
    ],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [
      {
        journeyEventId: 502,
        key: 1,
        id: 74,
        smsCampaignId: 113,
        smsCampaign: {
          id: 113,
          smsCampaignName: 'Neil Patel Webinar',
          senderName: 'C2C'
        },
        typeOfMessaging: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        isDyanmicSender: false,
        isTrackLink: false,
        isMultipart: false,
        status: 1,
        smsSendType: 1,
        backgroundJobId: null,
        timeZoneId: null,
        messagingRecords: null,
        messagingFilters: [
          {
            id: 25,
            smsConfigurationId: 74,
            filterId: 38,
            messagingFilterType: 1,
            isSelected: true
          }
        ],
        messagingLists: [
          {
            id: 52,
            listId: 119,
            smsConfigurationId: 74,
            listType: 3,
            isSelected: true
          }
        ],
        exclusionFilters: [],
        exclusionList: [],
        messagingListToExclude: [],
        leadScoreId: 0,
        leadGradeId: 0
      }
    ],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:04:54.8509251Z',
    creatorUserId: null
  },
  {
    id: 61,
    name: 'test Run',
    description: null,
    status: 'InActive',
    lastModificationTime: null,
    // tslint:disable-next-line:max-line-length
    journeyEventLinkJson: '{ \"class\": \"go.GraphLinksModel\",\n  \"linkFromPortIdProperty\": \"fromPort\",\n  \"linkToPortIdProperty\": \"toPort\",\n  \"nodeDataArray\": [ \n{\"key\":\"0\", \"color\":\"#229954\", \"name\":\"Start\", \"text\":\"Start\", \"category\":\"Start\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"190 90\"},\n{\"key\":\"1\", \"text\":\"Send email to selected list / filters\", \"source\":\"/Common/Images/journey/Email_left.png\", \"name\":\"Email\", \"color\":\"orange\", \"stroke\":\"#F47B3B\", \"loc\":\"470 150\"},\n{\"key\":\"4\", \"text\":\"Segment those who have opened / clicked email\", \"figure\":\"Diamond\", \"source\":\"/Common/Images/journey/Tracking_left.png\", \"name\":\"Tracking\", \"color\":\"white\", \"stroke\":\"#84A4D6\", \"loc\":\"910 230\"},\n{\"key\":\"5\", \"text\":\"Add certain records to selected list\", \"source\":\"/Common/Images/journey/Add_to_list_left.png\", \"name\":\"Add to List\", \"color\":\"white\", \"stroke\":\"#D9B650\", \"loc\":\"470 290\"},\n{\"key\":\"-1\", \"color\":\"#DC3C00\", \"name\":\"End\", \"text\":\"End\", \"category\":\"End\", \"figure\":\"circle\", \"height\":60, \"width\":60, \"statusIcon\":\"\", \"loc\":\"890 370\"}\n ],\n  \"linkDataArray\": [ \n{\"from\":\"0\", \"to\":\"1\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[190,115,190,125,190,150,256,150,322,150,332,150]},\n{\"from\":\"1\", \"to\":\"4\", \"fromPort\":\"B\", \"toPort\":\"L\", \"points\":[470,197,470,207,470,230,616,230,762,230,772,230]},\n{\"from\":\"4\", \"to\":\"5\", \"fromPort\":\"B\", \"toPort\":\"R\", \"visible\":true, \"points\":[910,277,910,287,910,290,764,290,618,290,608,290]},\n{\"from\":\"5\", \"to\":\"-1\", \"fromPort\":\"B\", \"toPort\":\"T\", \"points\":[470,337,470,347,734,347,734,335,890,335,890,345]}\n ]}',
    waitEventConfiguration: [],
    addToListEventConfiguration: [
      {
        id: 41,
        journeyEventId: 512,
        listId: 60,
        listName: 'SMS Demo',
        key: 5
      }
    ],
    decisionEventConfiguration: [],
    filter: null,
    trackingEventConfiguration: [
      {
        id: 34,
        journeyEventId: 511,
        journeyId: 61,
        key: 4,
        name: 'Tracking',
        isConditional: false,
        isNoConditionEvent: false,
        status: 0,
        trackOpenEmail: false,
        trackClickEmail: true
      }
    ],
    appEventConfiguration: [],
    timeInAppConfiguration: [],
    appActivityConfiguration: [],
    mobileAppActivityConfiguration: [],
    filterEventConfiguration: [],
    updateFieldEventConfiguration: [],
    emailConfiguration: null,
    pushEventConfigurations: [],
    inAppConfiguration: [],
    smsConfiguration: [],
    eventConfiguration: null,
    customTriggersConfiguration: [],
    pushStatusConfiguration: [],
    isDeleted: false,
    deleterUserId: null,
    deletionTime: null,
    lastModifierUserId: null,
    creationTime: '2020-06-26T15:05:16.5172549Z',
    creatorUserId: null
  },
];
