export const AutomationsMockData = {
  result: {
    totalCount: 27,
    items: [
      {
        id: 60,
        name: 'welcome email ua',
        description: 'welcome email ua',
        status: 'Active',
        lastModificationTime: '2020-06-19T01:35:54.897Z',
        creationTime: '2020-04-29T11:23:29.79Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 56,
        name: 'Test 17 April UA',
        description: null,
        status: 'Failed',
        lastModificationTime: '2020-05-26T05:25:03.307Z',
        creationTime: '2020-04-17T09:50:42.8733333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 15,
        name: 'automation-UA',
        description: 'newsletter filtered',
        status: 'Paused',
        lastModificationTime: '2020-05-21T06:31:03.037Z',
        creationTime: '2018-02-02T08:50:46.3133333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 55,
        name: 'Testing 17 2020',
        description: null,
        status: 'Paused',
        lastModificationTime: '2020-04-17T09:28:31.11Z',
        creationTime: '2020-04-17T08:09:17.9433333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 52,
        name: 'Demo Automation',
        description: null,
        status: 'Failed',
        lastModificationTime: '2019-11-25T10:26:39.603Z',
        creationTime: '2019-06-25T05:47:15.9066667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 51,
        name: 'GO Air Demo',
        description: null,
        status: 'Paused',
        lastModificationTime: '2019-07-25T08:31:12.887Z',
        creationTime: '2019-05-27T18:33:20.3866667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 33,
        name: 'Update Field',
        description: null,
        status: 'Failed',
        lastModificationTime: '2019-05-27T12:43:00.56Z',
        creationTime: '2019-04-02T10:30:35.1633333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 50,
        name: 'Test Demo',
        description: null,
        status: 'Failed',
        lastModificationTime: '2019-05-27T06:33:28.14Z',
        creationTime: '2019-05-27T06:23:20.2866667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 48,
        name: '7 May During',
        description: null,
        status: 'Failed',
        lastModificationTime: '2019-05-08T06:11:30.173Z',
        creationTime: '2019-05-07T06:51:28.1766667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 2,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 47,
        name: 'PreEvent7may',
        description: null,
        status: 'Failed',
        lastModificationTime: '2019-05-08T06:11:29.857Z',
        creationTime: '2019-05-07T06:44:30.97Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 2,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 46,
        name: 'DuringEventTest',
        description: null,
        status: 'Active',
        lastModificationTime: '2019-05-08T05:33:55.247Z',
        creationTime: '2019-04-25T06:05:16.36Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 2,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 44,
        name: 'duringevent',
        description: null,
        status: 'Paused',
        lastModificationTime: '2019-04-21T16:07:27.133Z',
        creationTime: '2019-04-21T16:02:54.2466667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 2,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 40,
        name: 'During11',
        description: null,
        status: 'Failed',
        lastModificationTime: '2019-04-16T05:11:58.38Z',
        creationTime: '2019-04-15T08:29:59.3633333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 2,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 31,
        name: 'Demo',
        description: null,
        status: 'Failed',
        lastModificationTime: '2019-03-27T17:57:57.187Z',
        creationTime: '2019-03-21T06:43:07.0833333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 32,
        name: 'Raw Office Survey',
        description: null,
        status: 'InActive',
        lastModificationTime: '2019-03-22T09:00:00.39Z',
        creationTime: '2019-03-22T06:48:24.4666667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 43,
        name: 'PreTest',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-04-18T04:50:40.8033333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 2,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 34,
        name: '11 april',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-04-11T12:04:38.7666667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 35,
        name: 'PreTestAutomaiton',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-04-15T06:21:56.3933333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 2,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 36,
        name: 'DuringEventAutomation',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-04-15T06:25:26.9Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 37,
        name: 'PostEventTest',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-04-15T06:32:19.1433333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 38,
        name: 'Pre11',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-04-15T08:23:16.1166667Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 2,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 39,
        name: 'post11',
        description: 'post11',
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-04-15T08:26:44.7533333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 53,
        name: '1',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2019-10-29T08:54:31.3533333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 1,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 54,
        name: 'Test Demo123',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2020-01-15T09:31:10.4733333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 58,
        name: 'Spring Summer Collection',
        description: 'An email campaign for spring summer collection',
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2020-04-27T09:30:18.2633333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 59,
        name: 'Demo Automation Sample',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2020-04-27T10:16:43.9533333Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 1,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 61,
        name: 'test Run',
        description: null,
        status: 'InActive',
        lastModificationTime: null,
        creationTime: '2020-05-27T06:56:27.11Z',
        journeyEventLinkJson: null,
        organizationUnitId: null,
        automationType: 0,
        eventAutomationType: 0,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
