export const FoldersMock = {
  result: [
    {
      folderId: 13,
      folderName: 'Groceries',
      lists: [
        {
          listId: 123,
          name: 'C',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 127,
          name: 'Demo list for Import',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 120,
          name: 'Demonstration List for Client',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 117,
          name: 'Email Lists',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 121,
          name: 'New Subscriber Welcome',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 126,
          name: 'Priyanka\'s mailing list',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 125,
          name: 'Rimpal\'s mailing list',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 119,
          name: 'Sample SMS List',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 118,
          name: 'Test John Doe Email List',
          description: null,
          folderId: 13,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        }
      ],
      landingPages: null,
      emailCampaigns: null,
      dynamicContents: null,
      landingPageTemplates: null,
      emailTemplates: null,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2020-06-22T09:01:41.1647249Z',
      creatorUserId: null,
      id: 0
    },
    {
      folderId: 14,
      folderName: 'Pharmacy',
      lists: [
        {
          listId: 124,
          name: 'test',
          description: null,
          folderId: 14,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        }
      ],
      landingPages: null,
      emailCampaigns: null,
      dynamicContents: null,
      landingPageTemplates: null,
      emailTemplates: null,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2020-06-22T09:01:41.1647249Z',
      creatorUserId: null,
      id: 0
    },
    {
      folderId: 17,
      folderName: 'Real Estate',
      lists: [],
      landingPages: null,
      emailCampaigns: null,
      dynamicContents: null,
      landingPageTemplates: null,
      emailTemplates: null,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2020-06-22T09:01:41.1647249Z',
      creatorUserId: null,
      id: 0
    },
    {
      folderId: 1,
      folderName: 'Unsorted',
      lists: [
        {
          listId: 97,
          name: 'BultImportList',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 95,
          name: 'campaign list',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 93,
          name: 'Corporate booking list',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 59,
          name: 'Demo List',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 89,
          name: 'First class frequent flyer',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 87,
          name: 'GO Air Link Click',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 88,
          name: 'Go Air Link not click',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 94,
          name: 'GO Air New List',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 86,
          name: 'Go Air SMS',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 96,
          name: 'Manoj Ladha',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 92,
          name: 'Mobile App',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 122,
          name: 'SamirList',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 91,
          name: 'Senior Citizens offere',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 60,
          name: 'SMS Demo',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 116,
          name: 'Test Emailing List',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 98,
          name: 'TestList',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 101,
          name: 'TestList4',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        },
        {
          listId: 90,
          name: 'Travelers',
          description: null,
          folderId: 1,
          folderName: null,
          type: null,
          lastModificationTime: null,
          creationTime: null,
          isDeleted: false,
          deleterUserId: null,
          deletionTime: null,
          lastModifierUserId: null,
          creatorUserId: null,
          id: 0
        }
      ],
      landingPages: null,
      emailCampaigns: null,
      dynamicContents: null,
      landingPageTemplates: null,
      emailTemplates: null,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2020-06-22T09:01:41.1647249Z',
      creatorUserId: null,
      id: 0
    }
  ],
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
