export const LandingPagesMock = {
  result: {
    totalCount: 8,
    items: [
      {
        pageNames: 'Sample Landing Page',
        externalPageDisplayName: 'SamplePage',
        pageDescription: 'Sample Landing page for testing',
        pageStatus: 'Draft',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/SamplePage.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: '2020-04-24T08:53:13.64Z',
        lastModifierUserId: 152,
        creationTime: '2020-04-24T08:49:25.497Z',
        creatorUserId: 152,
        id: 101
      },
      {
        pageNames: 'C2CWebinarEvent',
        externalPageDisplayName: 'C2CWebinarEvent',
        pageDescription: '',
        pageStatus: 'Published',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/C2CWebinarEvent.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: '2020-04-10T10:16:59.883Z',
        lastModifierUserId: 1,
        creationTime: '2020-04-10T10:15:58.33Z',
        creatorUserId: 1,
        id: 99
      },
      {
        pageNames: 'C2cEvent',
        externalPageDisplayName: 'C2cEvent',
        pageDescription: '',
        pageStatus: 'Draft',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/C2cEvent.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: '2020-04-10T09:53:19.093Z',
        lastModifierUserId: 1,
        creationTime: '2020-03-26T08:42:03.46Z',
        creatorUserId: 1,
        id: 98
      },
      {
        pageNames: 'Guru atman',
        externalPageDisplayName: 'G1',
        pageDescription: '',
        pageStatus: 'Published',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/G1.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: '2020-03-28T12:11:59.923Z',
        lastModifierUserId: 1,
        creationTime: '2019-11-12T15:40:26.64Z',
        creatorUserId: 120,
        id: 96
      },
      {
        pageNames: 'Event Registration',
        externalPageDisplayName: 'Evet29May',
        pageDescription: '',
        pageStatus: 'Draft',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/Evet29May.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: '2020-03-26T08:39:14.413Z',
        lastModifierUserId: 1,
        creationTime: '2018-05-29T11:24:01.88Z',
        creatorUserId: 1,
        id: 34
      },
      {
        pageNames: 'LandingTest',
        externalPageDisplayName: 'lptest',
        pageDescription: '',
        pageStatus: 'Published',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/lptest.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: '2020-01-24T19:31:28.79Z',
        lastModifierUserId: 1,
        creationTime: '2020-01-24T19:21:57.87Z',
        creatorUserId: 1,
        id: 97
      },
      {
        pageNames: 'RegistrationLanding',
        externalPageDisplayName: 'RegLanding',
        pageDescription: '',
        pageStatus: 'Published',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/RegLanding.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: '2018-05-18T10:37:29.493Z',
        lastModifierUserId: 1,
        creationTime: '2018-05-18T10:37:16.303Z',
        creatorUserId: 1,
        id: 33
      },
      {
        pageNames: 'New page',
        externalPageDisplayName: 'new',
        pageDescription: '',
        pageStatus: 'Draft',
        externalURL: 'http://storage-staging.campaigntocash.com/c2cuat/new.html?tenantId=73',
        organizationUnitId: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-04-18T10:24:15.17Z',
        creatorUserId: 1,
        id: 100
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
