export const AssetsMock = {
  result: {
    totalCount: 151,
    items: [
      {
        fileName: 'creative421.png',
        fileSize: 271645,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative421.png',
        lastModificationTime: null,
        creationTime: '2020-06-23T16:37:39.98Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 152,
        id: 193
      },
      {
        fileName: 'creative965.png',
        fileSize: 553120,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative965.png',
        lastModificationTime: null,
        creationTime: '2020-06-22T09:20:18.31Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 152,
        id: 192
      },
      {
        fileName: 'creative146.png',
        fileSize: 149795,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative146.png',
        lastModificationTime: null,
        creationTime: '2020-06-17T16:31:41.0033333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 152,
        id: 190
      },
      {
        fileName: 'creative620.png',
        fileSize: 425858,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative620.png',
        lastModificationTime: null,
        creationTime: '2020-06-17T13:49:21.9066667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 152,
        id: 189
      },
      {
        fileName: 'norton-antivirus-logo-png-powerful-antivirus-free-download.jpg',
        fileSize: 40088,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/norton-antivirus-logo-png-powerful-antivirus-free-download.jpg',
        lastModificationTime: null,
        creationTime: '2020-06-16T19:46:55.6933333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 188
      },
      {
        fileName: 'C2C.com Logo.png',
        fileSize: 2219,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/C2C.com Logo.png',
        lastModificationTime: null,
        creationTime: '2020-06-16T17:13:30.34Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 187
      },
      {
        fileName: 'localhost_6234_Application_Index1.PNG',
        fileSize: 42924,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/localhost_6234_Application_Index1.PNG',
        lastModificationTime: null,
        creationTime: '2020-06-16T16:04:30.2233333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 185
      },
      {
        fileName: 'creative681.png',
        fileSize: 434582,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative681.png',
        lastModificationTime: null,
        creationTime: '2020-06-16T13:35:03.93Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 152,
        id: 184
      },
      {
        fileName: '16-166020_indian-rupee-currency-price-tag-sale-shopping-svg.png',
        fileSize: 50540,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/16-166020_indian-rupee-currency-price-tag-sale-shopping-svg.png',
        lastModificationTime: null,
        creationTime: '2020-06-16T06:50:49.1266667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 183
      },
      {
        fileName: 's00002825.png',
        fileSize: 235638,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/s00002825.png',
        lastModificationTime: null,
        creationTime: '2020-06-16T06:49:30.3366667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 182
      },
      {
        fileName: '@@.jpg',
        fileSize: 85222,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/@@.jpg',
        lastModificationTime: null,
        creationTime: '2020-06-14T08:50:50.6966667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 160,
        id: 180
      },
      {
        fileName: 'Capture1.PNG',
        fileSize: 5480,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Capture1.PNG',
        lastModificationTime: null,
        creationTime: '2020-05-25T10:35:56.02Z',
        organizationUnitId: 48,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 164,
        id: 179
      },
      {
        fileName: 'Capture.PNG',
        fileSize: 87321,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Capture.PNG',
        lastModificationTime: null,
        creationTime: '2020-05-25T10:35:54.82Z',
        organizationUnitId: 48,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 164,
        id: 178
      },
      {
        fileName: 'creative854.png',
        fileSize: 753847,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative854.png',
        lastModificationTime: null,
        creationTime: '2020-04-27T13:13:16.8966667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 176
      },
      {
        fileName: 'creative927.png',
        fileSize: 553931,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative927.png',
        lastModificationTime: null,
        creationTime: '2020-04-27T13:09:23.91Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 175
      },
      {
        fileName: 'creative259.png',
        fileSize: 1690976,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative259.png',
        lastModificationTime: null,
        creationTime: '2020-04-27T12:57:15.2566667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 174
      },
      {
        fileName: 'creative517.png',
        fileSize: 434582,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative517.png',
        lastModificationTime: null,
        creationTime: '2020-04-27T12:50:10.13Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 173
      },
      {
        fileName: 'creative209.png',
        fileSize: 429870,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative209.png',
        lastModificationTime: null,
        creationTime: '2020-04-27T12:42:16.2133333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 172
      },
      {
        fileName: 'creative121.png',
        fileSize: 2918885,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative121.png',
        lastModificationTime: null,
        creationTime: '2020-04-27T03:47:45.7433333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 152,
        id: 171
      },
      {
        fileName: 'creative576.png',
        fileSize: 289449,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative576.png',
        lastModificationTime: null,
        creationTime: '2020-04-27T03:39:19.6Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 152,
        id: 170
      },
      {
        fileName: 'creative867.png',
        fileSize: 516130,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative867.png',
        lastModificationTime: null,
        creationTime: '2020-04-24T09:14:39.45Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 169
      },
      {
        fileName: 'creative366.png',
        fileSize: 516130,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative366.png',
        lastModificationTime: null,
        creationTime: '2020-04-24T09:12:04.8633333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 168
      },
      {
        fileName: 'creative649.png',
        fileSize: 266113,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative649.png',
        lastModificationTime: null,
        creationTime: '2020-04-16T09:28:42.9633333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 166
      },
      {
        fileName: '1digitla marketing.png',
        fileSize: 218775,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/1digitla marketing.png',
        lastModificationTime: null,
        creationTime: '2020-03-12T13:20:09.45Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 164
      },
      {
        fileName: 'creative268.png',
        fileSize: 100948,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/creative268.png',
        lastModificationTime: null,
        creationTime: '2020-01-07T00:41:31.6466667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 163
      },
      {
        fileName: 'image.jpg',
        fileSize: 100948,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/image.jpg',
        lastModificationTime: null,
        creationTime: '2020-01-07T00:34:27.0366667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 162
      },
      {
        fileName: 'enjoying-facebook-phone-laptop_23-2147651315.jpg',
        fileSize: 88184,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/enjoying-facebook-phone-laptop_23-2147651315.jpg',
        lastModificationTime: null,
        creationTime: '2019-12-03T11:08:22.45Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 161
      },
      {
        fileName: '3 bhk fm.jpg',
        fileSize: 401590,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/3 bhk fm.jpg',
        lastModificationTime: null,
        creationTime: '2019-11-12T16:01:33.2966667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 120,
        id: 160
      },
      {
        fileName: 'dashboard.png',
        fileSize: 84028,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/dashboard.png',
        lastModificationTime: null,
        creationTime: '2019-10-30T12:18:28.3033333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 159
      },
      {
        fileName: 'Untitled Design.png',
        fileSize: 330018,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Untitled Design.png',
        lastModificationTime: null,
        creationTime: '2019-10-17T10:41:05.8533333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 158
      },
      {
        fileName: '260296477Campaightocash-01 (1).png',
        fileSize: 597752,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/260296477Campaightocash-01 (1).png',
        lastModificationTime: null,
        creationTime: '2019-09-30T10:56:38.88Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 157
      },
      {
        fileName: 'DesktopBanner3.jpg',
        fileSize: 252388,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/DesktopBanner3.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:51:23.6966667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 156
      },
      {
        fileName: 'Amenities6.svg',
        fileSize: 2021,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Amenities6.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:53.6733333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 155
      },
      {
        fileName: 'Amenities4.svg',
        fileSize: 4446,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Amenities4.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:52.61Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 154
      },
      {
        fileName: 'ProposedMetroPlan.jpg',
        fileSize: 118948,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/ProposedMetroPlan.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:51.7833333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 153
      },
      {
        fileName: 'Skyline_xl.jpg',
        fileSize: 175754,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Skyline_xl.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:50.6066667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 152
      },
      {
        fileName: 'ProjectDetails_xl.jpg',
        fileSize: 204523,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/ProjectDetails_xl.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:49.28Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 151
      },
      {
        fileName: 'Amenities2.svg',
        fileSize: 1957,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Amenities2.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:48.36Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 150
      },
      {
        fileName: 'Amenities3.svg',
        fileSize: 1947,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Amenities3.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:47.47Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 149
      },
      {
        fileName: 'LocationMap.jpg',
        fileSize: 97607,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/LocationMap.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:46.4533333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 148
      },
      {
        fileName: 'Gurukrupa.svg',
        fileSize: 9234,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Gurukrupa.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:45.6233333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 147
      },
      {
        fileName: 'Guru-Atman.svg',
        fileSize: 17140,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/Guru-Atman.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:44.7333333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 146
      },
      {
        fileName: 'FuturisticLocations5.svg',
        fileSize: 2107,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FuturisticLocations5.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:43.78Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 145
      },
      {
        fileName: 'FloorPlan-02.jpg',
        fileSize: 344086,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FloorPlan-02.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:42.9033333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 144
      },
      {
        fileName: 'FuturisticLocations4.svg',
        fileSize: 1551,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FuturisticLocations4.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:41.9933333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 143
      },
      {
        fileName: 'FuturisticLocations3.svg',
        fileSize: 2039,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FuturisticLocations3.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:40.9166667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 142
      },
      {
        fileName: 'FuturisticLocations2.svg',
        fileSize: 972,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FuturisticLocations2.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:39.7633333Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 141
      },
      {
        fileName: 'FuturisticLocations1.svg',
        fileSize: 1062,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FuturisticLocations1.svg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:38.4966667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 140
      },
      {
        fileName: 'FloorPlan-06.jpg',
        fileSize: 225551,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FloorPlan-06.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:37.3366667Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 139
      },
      {
        fileName: 'FloorPlan-05.jpg',
        fileSize: 236328,
        imgPhysicalPath: 'http://storage-staging.campaigntocash.com/c2cuat/FloorPlan-05.jpg',
        lastModificationTime: null,
        creationTime: '2019-09-30T06:11:35.97Z',
        organizationUnitId: 1,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: 1,
        id: 138
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
