export const EventListsMockData = {
  result: {
    totalCount: 21,
    items: [
      {
        listId: 110,
        name: 'C2CWebinar2020- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2020-04-10T11:38:18.6866667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 109,
        name: 'C2CWebinar2020- NotRegistered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2020-04-10T11:38:17.8Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 83,
        name: 'Event 7 may- Attendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-05-07T06:50:49.9666667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 82,
        name: 'Event 7 may- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-05-07T06:50:49.8266667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 81,
        name: 'Event 7 may- NotRegistered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-05-07T06:50:49.5966667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 80,
        name: 'EventTestRegister- Attendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-25T11:05:03.34Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 79,
        name: 'EventTestRegister- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-25T11:05:03.26Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 78,
        name: 'EventTestRegister- NotRegistered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-25T11:05:03.1033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 76,
        name: 'EventNew1- NonAttendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-25T06:04:31.9466667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 75,
        name: 'EventNew1- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-25T06:04:31.5133333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 74,
        name: 'EventNew1- Attendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-25T06:01:55.8433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 73,
        name: 'Event campaign UA 1- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-21T16:27:39.8Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 72,
        name: 'EventNew- NonAttendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-21T16:02:38.2633333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 71,
        name: 'EventNew- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-21T16:02:33.5966667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 70,
        name: 'Event campaign UA 2- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-21T16:01:00.75Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 69,
        name: 'TestEvent- NonAttendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-20T17:43:30.77Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 68,
        name: 'TestEvent- Registered',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-20T17:43:30.0666667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 65,
        name: 'Event campaign UA 2- NonAttendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-15T06:31:59.79Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 64,
        name: 'Event campaign UA 2- Attendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-15T06:31:59.3Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 63,
        name: 'Event campaign UA 1- NonAttendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-11T12:04:20.38Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 62,
        name: 'Event campaign UA 1- Attendee',
        description: null,
        folderId: null,
        folderName: null,
        type: 'Event',
        lastModificationTime: null,
        creationTime: '2019-04-11T12:04:19.9333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
