export const CustomFieldsMock = {
  result: {
    totalCount: 28,
    items: [
      {
        name: null,
        displayName: 'Prashant',
        mappedDBField: 'TextField75',
        defaultValue: 'Assginment',
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-05-25T06:10:11.05Z',
        creatorUserId: 1,
        id: 29
      },
      {
        name: null,
        displayName: 'ashish',
        mappedDBField: 'TextField76',
        defaultValue: 'AF',
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-05-24T13:58:27.037Z',
        creatorUserId: 1,
        id: 28
      },
      {
        name: null,
        displayName: 'fdfd',
        mappedDBField: 'TextField77',
        defaultValue: 'e',
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-05-23T12:46:42.663Z',
        creatorUserId: 160,
        id: 27
      },
      {
        name: null,
        displayName: 'Requirement',
        mappedDBField: 'TextField78',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-04-10T19:15:05.253Z',
        creatorUserId: 149,
        id: 25
      },
      {
        name: null,
        displayName: 'Pincode',
        mappedDBField: 'TextField79',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-04-10T19:14:26.867Z',
        creatorUserId: 149,
        id: 24
      },
      {
        name: null,
        displayName: 'Other number3',
        mappedDBField: 'TextField8',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-04-10T19:14:08.95Z',
        creatorUserId: 149,
        id: 23
      },
      {
        name: null,
        displayName: 'Other Number2',
        mappedDBField: 'TextField80',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-04-10T19:13:56.723Z',
        creatorUserId: 149,
        id: 22
      },
      {
        name: null,
        displayName: 'Other Number1',
        mappedDBField: 'TextField81',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-04-10T19:13:38.94Z',
        creatorUserId: 149,
        id: 21
      },
      {
        name: null,
        displayName: 'Source',
        mappedDBField: 'TextField82',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-04-10T19:13:29Z',
        creatorUserId: 149,
        id: 20
      },
      {
        name: null,
        displayName: 'Telecom Operator',
        mappedDBField: 'TextField83',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-01-12T03:55:45.533Z',
        creatorUserId: 1,
        id: 19
      },
      {
        name: null,
        displayName: 'Database Name',
        mappedDBField: 'TextField84',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-01-12T03:55:22.96Z',
        creatorUserId: 1,
        id: 18
      },
      {
        name: null,
        displayName: 'Work Permit',
        mappedDBField: 'TextField85',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:09:21.277Z',
        creatorUserId: 101,
        id: 17
      },
      {
        name: null,
        displayName: 'Marital Status',
        mappedDBField: 'TextField86',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:09:10.717Z',
        creatorUserId: 101,
        id: 16
      },
      {
        name: null,
        displayName: 'Post Graduation University Name',
        mappedDBField: 'TextField87',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:09:00.337Z',
        creatorUserId: 101,
        id: 15
      },
      {
        name: null,
        displayName: 'Post Graduation Specialization',
        mappedDBField: 'TextField88',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:08:49.817Z',
        creatorUserId: 101,
        id: 14
      },
      {
        name: null,
        displayName: 'Under Graduation Year',
        mappedDBField: 'TextField89',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:08:40.18Z',
        creatorUserId: 101,
        id: 13
      },
      {
        name: null,
        displayName: 'Under Graduation Specialization',
        mappedDBField: 'TextField9',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:08:30.407Z',
        creatorUserId: 101,
        id: 12
      },
      {
        name: null,
        displayName: 'Under Graduation Degree',
        mappedDBField: 'TextField90',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:08:18.26Z',
        creatorUserId: 101,
        id: 11
      },
      {
        name: null,
        displayName: 'Current Company Name',
        mappedDBField: 'TextField91',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:08:06.333Z',
        creatorUserId: 101,
        id: 10
      },
      {
        name: null,
        displayName: 'Total Experience',
        mappedDBField: 'TextField92',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T05:07:52.897Z',
        creatorUserId: 101,
        id: 9
      },
      {
        name: null,
        displayName: 'Notice Period',
        mappedDBField: 'TextField93',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:37:10.93Z',
        creatorUserId: 101,
        id: 8
      },
      {
        name: null,
        displayName: 'Date of Birth',
        mappedDBField: 'TextField94',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:37:03.253Z',
        creatorUserId: 101,
        id: 7
      },
      {
        name: null,
        displayName: 'Post Graduation Year',
        mappedDBField: 'TextField95',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:36:54.077Z',
        creatorUserId: 101,
        id: 6
      },
      {
        name: null,
        displayName: 'Post Graduation Degree',
        mappedDBField: 'TextField96',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:36:45.013Z',
        creatorUserId: 101,
        id: 5
      },
      {
        name: null,
        displayName: 'Annual Salary',
        mappedDBField: 'TextField97',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:36:35.253Z',
        creatorUserId: 101,
        id: 4
      },
      {
        name: null,
        displayName: 'Industry',
        mappedDBField: 'TextField98',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:36:27.043Z',
        creatorUserId: 101,
        id: 3
      },
      {
        name: null,
        displayName: 'Functional Area',
        mappedDBField: 'TextField99',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:36:16.98Z',
        creatorUserId: 101,
        id: 2
      },
      {
        name: null,
        displayName: 'Requirement Name',
        mappedDBField: 'TextField1',
        defaultValue: null,
        fieldDataType: 'Text',
        isSelected: false,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2019-09-05T04:36:06.56Z',
        creatorUserId: 101,
        id: 1
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
