export const EventsMockData = {
  result: {
    totalCount: 15,
    items: [
      {
        eventName: 'gh',
        eventSubject: 'jhgfjh',
        eventStartDate: '2020-06-04T09:23:00Z',
        eventEndDate: '2020-06-18T10:23:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 34
      },
      {
        eventName: 'C2CWebinar2020',
        eventSubject: 'C2CWebinar2020',
        eventStartDate: '2020-04-29T00:00:00Z',
        eventEndDate: '2020-04-29T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 33
      },
      {
        eventName: 'C2C Webinar',
        eventSubject: 'C2C Webinar',
        eventStartDate: '2020-04-23T00:00:00Z',
        eventEndDate: '2020-04-23T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: 'pune',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 32
      },
      {
        eventName: 'NewRegisterEvent2020',
        eventSubject: 'NewregisterEvent2020',
        eventStartDate: '2020-04-01T18:30:00Z',
        eventEndDate: '2020-04-03T11:30:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 31
      },
      {
        eventName: 'NewEvent2020',
        eventSubject: 'NewEvent2020',
        eventStartDate: '2020-04-01T18:30:00Z',
        eventEndDate: '2020-04-03T11:30:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: 'xyz',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 30
      },
      {
        eventName: 'New Event',
        eventSubject: 'New Event',
        eventStartDate: '2020-01-11T20:30:00Z',
        eventEndDate: '2020-01-11T21:30:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 29
      },
      {
        eventName: 'Go Air Demo',
        eventSubject: 'Demo',
        eventStartDate: '2019-05-28T00:00:00Z',
        eventEndDate: '2019-05-28T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 28
      },
      {
        eventName: 'Event 7 may',
        eventSubject: 'Event 7 May',
        eventStartDate: '2019-05-08T00:00:00Z',
        eventEndDate: '2019-05-08T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 27
      },
      {
        eventName: 'EventTestRegister',
        eventSubject: 'EventTestRegister',
        eventStartDate: '2019-05-24T00:00:00Z',
        eventEndDate: '2019-05-24T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: 'pune',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 26
      },
      {
        eventName: 'EventNew1',
        eventSubject: 'EventNew1',
        eventStartDate: '2019-04-26T18:30:00Z',
        eventEndDate: '2019-04-26T11:30:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: 'pune',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 25
      },
      {
        eventName: 'EventNew',
        eventSubject: 'EventNew',
        eventStartDate: '2019-04-22T18:30:00Z',
        eventEndDate: '2019-04-23T11:30:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 24
      },
      {
        eventName: 'Demo Event',
        eventSubject: 'Demo Event',
        eventStartDate: '2019-03-21T00:00:00Z',
        eventEndDate: '2019-03-21T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: '',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 21
      },
      {
        eventName: 'Webinar Event for Demo',
        eventSubject: 'Webinar event - Speaker - Herry',
        eventStartDate: '2020-04-16T00:00:00Z',
        eventEndDate: '2020-05-29T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: 'gotometing.com/54496921',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 14
      },
      {
        eventName: 'Event campaign UA 2',
        eventSubject: 'Closing General Session with Lunch',
        eventStartDate: '2018-08-01T03:30:00Z',
        eventEndDate: '2018-09-22T18:30:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: 'https://global.gotomeeting.com/join/589229253',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 13
      },
      {
        eventName: 'General Meeting',
        eventSubject: 'Closing General Session with Lunch invitation',
        eventStartDate: '2020-02-06T00:00:00Z',
        eventEndDate: '2020-04-01T00:00:00Z',
        eventStartTime: null,
        displayName: null,
        fromAddressId: 0,
        replyAddressId: 0,
        eventEndTime: null,
        location: 'https://global.gotomeeting.com/join/589229253',
        eventBody: null,
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: '2020-06-22T09:58:26.9587618Z',
        creatorUserId: null,
        id: 12
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
