import { Event } from '@app-models/event';

export const EventsMockData: Event[] = [
  {
    id: 1,
    name: 'C2CWebinar2020',
    subject: 'C2CWebinar2020',
    start_date: 'Apr 29, 2020 2:00:00 AM',
    end_date: 'Apr 29, 2020 2:00:00 AM',
    display_name: 'campaigntocash',
    folder: 'groceries',
    location: '',
    template: 'aa',
  },
  {
    id: 2,
    name: 'C2C Webinar',
    subject: 'C2C Webinar',
    start_date: 'Apr 23, 2020 2:00:00 AM',
    end_date: 'Apr 23, 2020 2:00:00 AM',
    display_name: 'campaigntocash',
    folder: 'pharmacy',
    template: '',
    location: '',
  },
  {
    id: 3,
    name: 'NewRegisterEvent2020',
    subject: 'NewRegisterEvent2020',
    start_date: 'Apr 1, 2020 8:30:00 PM',
    end_date: 'Apr 3, 2020 1:30:00 PM',
    display_name: 'palskem',
    folder: 'realestate',
    template: 'oo',
    location: '',
  },
  {
    id: 4,
    name: 'NewEvent2020',
    subject: 'NewEvent2020',
    start_date: 'Apr 1, 2020 8:30:00 PM',
    end_date: 'Apr 3, 2020 1:30:00 PM',
    display_name: 'campaigntocash',
    folder: 'groceries',
    template: 'nn',
    location: '',
  },
  {
    id: 5,
    name: 'Go Air Demo',
    subject: 'Demo',
    start_date: 'May 28, 2019 2:00:00 AM',
    end_date: 'May 28, 2019 2:00:00 AM',
    display_name: 'campaigntocash',
    folder: 'pharmacy',
    template: 'll',
    location: '',
  },
  {
    id: 6,
    name: 'C2CWebinar2020',
    subject: 'C2CWebinar2020',
    start_date: 'Apr 29, 2020 2:00:00 AM',
    end_date: 'Apr 29, 2020 2:00:00 AM',
    display_name: 'campaigntocash',
    folder: 'groceries',
    template: 'mm',
    location: '',
  },
  {
    id: 7,
    name: 'Event 7 may',
    subject: 'Event 7 may',
    start_date: 'May 8, 2019 2:00:00 AM',
    end_date: 'May 8, 2019 2:00:00 AM',
    display_name: 'palskem',
    folder: 'realestate',
    template: 'kk',
    location: '',
  },
  {
    id: 8,
    name: 'EventTestRegister',
    subject: 'EventTestRegister',
    start_date: 'May 24, 2019 2:00:00 AM',
    end_date: 'May 24, 2019 2:00:00 AM',
    display_name: 'palskem',
    folder: 'realestate',
    template: 'jj',
    location: '',
  },
  {
    id: 9,
    name: 'EventNew1',
    subject: 'EventNew1',
    start_date: 'Apr 26, 2019 1:30:00 PM',
    end_date: 'Apr 26, 2019 8:30:00 PM',
    display_name: 'campaigntocash',
    folder: 'pharmacy',
    template: 'ii',
    location: '',
  },
  {
    id: 10,
    name: 'EventNew',
    subject: 'EventNew',
    start_date: 'Apr 22, 2019 8:30:00 PM',
    end_date: 'Apr 23, 2019 1:30:00 PM',
    display_name: 'campaigntocash',
    folder: 'groceries',
    template: 'hh',
    location: '',
  },
  {
    id: 11,
    name: 'Demo Event',
    subject: 'Demo Event',
    start_date: 'Mar 21, 2019 1:00:00 AM',
    end_date: 'Mar 21, 2019 1:00:00 AM',
    display_name: 'palskem',
    folder: 'realestate',
    template: 'gg',
    location: '',
  },
  {
    id: 12,
    name: 'Webinar Event for Demo',
    subject: 'Webinar event - Speaker - Herry',
    start_date: 'Apr 16, 2020 2:00:00 AM',
    end_date: 'May 29, 2020 2:00:00 AM',
    display_name: 'palskem',
    folder: 'pharmacy',
    template: 'ff',
    location: '',
  },
  {
    id: 13,
    name: 'Event campaign UA 2',
    subject: 'Closing General Session with Lunch',
    start_date: 'Aug 1, 2018 5:30:00 AM',
    end_date: 'Sep 22, 2018 8:30:00 PM',
    display_name: 'campaigntocash',
    folder: 'realestate',
    template: 'ee',
    location: '',
  },
  {
    id: 14,
    name: 'General Meeting',
    subject: 'Closing General Session with Lunch invitation',
    start_date: 'Feb 6, 2020 1:00:00 AM',
    end_date: 'Apr 1, 2020 2:00:00 AM',
    display_name: 'campaigntocash',
    folder: 'pharmacy',
    template: 'aa',
    location: '',
  },
];
