export const ListsMockData = {
  result: {
    totalCount: 34,
    items: [
      {
        listId: 127,
        name: 'Demo list for Import',
        description: 'List created to demo file import',
        folderId: 13,
        folderName: 'Groceries',
        type: 'Mailing',
        lastModificationTime: '2020-05-28T02:44:48.083Z',
        creationTime: '2020-05-27T06:58:53.6266667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 121,
        name: 'New Subscriber Welcome',
        description: 'Welcome Email List',
        folderId: 13,
        folderName: 'Groceries',
        type: 'Mailing',
        lastModificationTime: '2020-04-30T09:59:44.92Z',
        creationTime: '2020-04-29T10:45:05.65Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 122,
        name: 'SamirList',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-05-12T13:47:43.8133333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 123,
        name: 'C',
        description: '',
        folderId: 13,
        folderName: 'Groceries',
        type: 'SMS',
        lastModificationTime: null,
        creationTime: '2020-05-25T06:07:54.6333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 124,
        name: 'test',
        description: 'test',
        folderId: 14,
        folderName: 'Pharmacy',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-05-26T01:46:26.3933333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 125,
        name: 'Rimpal\'s mailing list',
        description: '',
        folderId: 13,
        folderName: 'Groceries',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-05-26T05:18:54.2433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 126,
        name: 'Priyanka\'s mailing list',
        description: '',
        folderId: 13,
        folderName: 'Groceries',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-05-26T05:19:07.4Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 55,
        name: 'List for Newsletters',
        description: 'send to website subscribers',
        folderId: 8,
        folderName: 'For Demo',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-01-17T19:31:56.4333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 56,
        name: 'List for Survey',
        description: 'Send analytics tool survey',
        folderId: 8,
        folderName: 'For Demo',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-01-17T19:35:00.8766667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 57,
        name: 'List of CMO s -Inc500',
        description: 'List of CMO s -Inc500',
        folderId: 8,
        folderName: 'For Demo',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-01-17T19:35:57.3733333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 59,
        name: 'Demo List',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-03-21T06:38:31.2366667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 60,
        name: 'SMS Demo',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'SMS',
        lastModificationTime: null,
        creationTime: '2019-03-21T07:03:21.1233333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 67,
        name: 'UATTestingList',
        description: '',
        folderId: 6,
        folderName: 'ajay',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-04-19T06:53:17.4266667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 77,
        name: 'NewEventListTest',
        description: '',
        folderId: 6,
        folderName: 'ajay',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-04-25T09:27:11.7033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 85,
        name: 'Uspheria Campaign tracking list',
        description: '',
        folderId: 8,
        folderName: 'For Demo',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-05-24T20:09:35.2033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 86,
        name: 'Go Air SMS',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'SMS',
        lastModificationTime: null,
        creationTime: '2019-05-27T09:46:12.1033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 87,
        name: 'GO Air Link Click',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-05-27T18:30:10.2066667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 88,
        name: 'Go Air Link not click',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-05-27T18:30:23.89Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 89,
        name: 'First class frequent flyer',
        description: 'First class and business class traveler',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-06-05T07:42:48.1566667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 90,
        name: 'Travelers',
        description: 'weekend gateways',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-06-05T08:37:42.77Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 91,
        name: 'Senior Citizens offere',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-06-05T08:38:21.5533333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 92,
        name: 'Mobile App',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-06-05T08:39:22.0433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 93,
        name: 'Corporate booking list',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-06-05T09:22:44.2166667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 94,
        name: 'GO Air New List',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-06-06T10:00:12.2366667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 95,
        name: 'campaign list',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2019-11-25T10:22:19.4366667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 96,
        name: 'Manoj Ladha',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-01-15T19:46:29.4633333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 97,
        name: 'BultImportList',
        description: 'TestList',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-01-17T11:51:58.3433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 98,
        name: 'TestList',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-01-17T13:00:23.9233333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 101,
        name: 'TestList4',
        description: '',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-01-17T13:42:07.6433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 116,
        name: 'Test Emailing List',
        description: 'A test emailing list for demo',
        folderId: 1,
        folderName: 'Unsorted',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-04-22T08:36:54.15Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 117,
        name: 'Email Lists',
        description: 'Email List',
        folderId: 13,
        folderName: 'Groceries',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-04-23T10:40:53.6066667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 118,
        name: 'Test John Doe Email List',
        description: 'Test Email List for AKR',
        folderId: 13,
        folderName: 'Groceries',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-04-23T12:00:57.22Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 119,
        name: 'Sample SMS List',
        description: 'Sample List',
        folderId: 13,
        folderName: 'Groceries',
        type: 'SMS',
        lastModificationTime: null,
        creationTime: '2020-04-24T04:08:03.65Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      },
      {
        listId: 120,
        name: 'Demonstration List for Client',
        description: 'A sample demonstration list for client demo',
        folderId: 13,
        folderName: 'Groceries',
        type: 'Mailing',
        lastModificationTime: null,
        creationTime: '2020-04-27T07:38:38.0366667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null,
        id: 0
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
