export const ReportEmailCampaignsMock = {
  result: {
    totalCount: 474,
    items: [
      {
        id: 679,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Paused',
        lastModificationTime: '2020-04-09T13:38:19.203Z',
        creationTime: '2020-04-09T13:38:14.6866667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 678,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-09T13:29:24.16Z',
        creationTime: '2020-04-09T13:29:19.04Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 677,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-09T13:03:33.8Z',
        creationTime: '2020-04-09T13:03:29.7766667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 676,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-09T12:53:03.307Z',
        creationTime: '2020-04-09T12:53:01.87Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 675,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-09T11:11:44.723Z',
        creationTime: '2020-04-09T11:11:44.12Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 674,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-09T11:07:40.117Z',
        creationTime: '2020-04-09T11:07:39.4166667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 673,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-09T11:03:36.137Z',
        creationTime: '2020-04-09T11:03:35.4166667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 672,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Test123',
        emailSubject: 'Test33',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-09T10:59:46.143Z',
        creationTime: '2020-04-09T10:59:44.47Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 668,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'C2C Webinar',
        emailSubject: 'C2C Webinar',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Active',
        lastModificationTime: '2020-04-09T09:26:03.96Z',
        creationTime: '2020-04-09T09:25:59.4333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 663,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewRegisterEvent2020',
        emailSubject: 'NewregisterEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Active',
        lastModificationTime: '2020-03-26T08:55:33.053Z',
        creationTime: '2020-03-26T08:55:29.05Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 662,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewRegisterEvent2020',
        emailSubject: 'NewregisterEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-03-26T08:53:30.613Z',
        creationTime: '2020-03-26T08:53:25.1433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 661,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-03-26T06:49:38.543Z',
        creationTime: '2020-03-26T06:49:33.4566667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 660,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Active',
        lastModificationTime: '2020-03-24T13:44:36.543Z',
        creationTime: '2020-03-24T13:44:35.7033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 659,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-03-24T13:39:40.093Z',
        creationTime: '2020-03-24T13:39:39.1566667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 658,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-03-24T13:02:06.48Z',
        creationTime: '2020-03-24T13:02:05.24Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 657,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Samir test Campaign',
        emailSubject: 'Test Campaign',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Failed',
        lastModificationTime: '2020-03-24T09:38:11.397Z',
        creationTime: '2020-03-24T09:38:06.7333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 656,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-03-24T09:17:57.113Z',
        creationTime: '2020-03-24T09:17:53.2466667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 655,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: '2020-03-24T09:15:55.967Z',
        creationTime: '2020-03-24T09:15:51.85Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 654,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Active',
        lastModificationTime: '2020-03-24T08:56:59.517Z',
        creationTime: '2020-03-24T08:56:55.1466667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 653,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Active',
        lastModificationTime: '2020-03-24T08:56:47.197Z',
        creationTime: '2020-03-24T08:56:42.9666667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 652,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEvent2020',
        emailSubject: 'NewEvent2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Active',
        lastModificationTime: '2020-03-24T08:56:45.817Z',
        creationTime: '2020-03-24T08:56:38.6033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 651,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'NewEmailCampaign2020',
        emailSubject: 'NewEmailCampaign2020',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-03-23T13:19:12.983Z',
        creationTime: '2020-03-23T13:19:12.5233333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 650,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'GurukrupaDemo',
        emailSubject: 'GurukrupaDemo',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: '2020-03-19T14:22:52.187Z',
        creationTime: '2020-03-19T14:22:50.3566667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 649,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Gurukrupa Demo',
        emailSubject: 'Gurukrupa Demo',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-03-17T16:19:30.03Z',
        creationTime: '2020-03-17T16:19:28.73Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 646,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Lead Nurturing Campaign',
        emailSubject: 'Last Chance to Avail Free Offer!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2020-03-25T14:13:20.457Z',
        status: 'Scheduled',
        lastModificationTime: '2020-01-20T14:14:21.79Z',
        creationTime: '2020-01-20T14:14:18.3333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 644,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Lead Nurturing Campaign',
        emailSubject: 'Last Chance to Avail Free Offer!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2020-01-18T14:36:39.163Z',
        status: 'Scheduled',
        lastModificationTime: '2020-01-17T14:36:11.347Z',
        creationTime: '2020-01-17T14:36:11.2233333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 643,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Lead Nurturing Campaign',
        emailSubject: 'Last Chance to Avail Free Offer!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: '2020-01-17T14:35:19.963Z',
        creationTime: '2020-01-17T14:35:19.8733333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 642,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Lead Nurturing Campaign',
        emailSubject: 'Last Chance to Avail Free Offer!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: '2020-01-17T14:33:11.03Z',
        creationTime: '2020-01-17T14:33:10.92Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 641,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Lead Nurturing Campaign',
        emailSubject: 'Last Chance to Avail Free Offer!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: '2020-01-17T14:27:26.157Z',
        creationTime: '2020-01-17T14:27:25.6333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 640,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Hurry! Only 5 apartment left',
        emailSubject: 'Hurry! Only 5 apartment left',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: '2020-01-15T12:58:47.21Z',
        creationTime: '2020-01-15T12:58:15.08Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 638,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'New Event',
        emailSubject: 'New Event',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-01-11T04:12:02.907Z',
        creationTime: '2020-01-11T04:12:02.7933333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 637,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'New Event',
        emailSubject: 'New Event',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-01-11T04:10:51.387Z',
        creationTime: '2020-01-11T04:10:50.8233333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 636,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-01-07T13:26:39.787Z',
        creationTime: '2020-01-07T13:26:38.9866667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 635,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-11-26T06:43:10.39Z',
        creationTime: '2019-11-26T06:43:09.97Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 634,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-11-25T16:25:38.98Z',
        creationTime: '2019-11-25T16:25:37.52Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 633,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-12-07T10:04:51.84Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T10:04:17.34Z',
        creationTime: '2019-11-15T10:04:17.09Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 632,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Study in demo sample for Demo',
        emailSubject: 'Last chance`` to register!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-12-19T05:37:24.363Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T09:56:57.52Z',
        creationTime: '2019-11-15T09:56:57.4266667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 631,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Go Air Flight Offers',
        emailSubject: 'Offers- New Registration',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-12-17T22:38:45.503Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T09:55:22.297Z',
        creationTime: '2019-11-15T09:55:22.0166667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 630,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Hurry! Only 5 apartment left',
        emailSubject: 'Hurry! Only 5 apartment left',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-11-20T09:33:45.74Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T09:33:05.813Z',
        creationTime: '2019-11-15T09:33:05.7533333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 629,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Gurukrupa Demo',
        emailSubject: 'Gurukrupa Demo',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-11-15T19:30:06.07Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T09:32:36.277Z',
        creationTime: '2019-11-15T09:32:35.8833333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 628,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'GurukrupaDemo',
        emailSubject: 'GurukrupaDemo',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-11-09T10:01:05.09Z',
        creationTime: '2019-11-09T10:01:03.17Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 627,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'TestCampaignWeb',
        emailSubject: 'TestCampaignWeb',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T12:00:56.497Z',
        creationTime: '2019-10-17T12:00:54.4633333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 626,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T12:00:19.277Z',
        creationTime: '2019-10-17T12:00:18.6033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 625,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T11:37:01.43Z',
        creationTime: '2019-10-17T11:36:57.1466667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 624,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T11:12:14.5Z',
        creationTime: '2019-10-17T11:12:14.44Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 623,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T11:05:49.393Z',
        creationTime: '2019-10-17T11:05:45.11Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 622,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'GurukrupaDemo',
        emailSubject: 'GurukrupaDemo',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T10:35:21.64Z',
        creationTime: '2019-10-17T10:35:21.56Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 620,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T10:32:54.177Z',
        creationTime: '2019-10-17T10:32:49.8266667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 619,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T10:14:28.177Z',
        creationTime: '2019-10-17T10:14:28.1033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 618,
        emailCampaignId: 0,
        emailCampaign: null,
        emailName: 'Introductory Campaign',
        emailSubject: 'Introducing Campaigntocash - Software as a Marketing Solution!',
        typeOfMailing: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-10-17T10:04:58.937Z',
        creationTime: '2019-10-17T10:04:58.8766667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
