export const ReportSmsCampaignsMock = {
  result: {
    totalCount: 21,
    items: [
      {
        id: 74,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Neil Patel Webinar',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: null,
        creationTime: '2020-04-27T10:16:44.0666667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 73,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Sample Test',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-25T06:38:53.19Z',
        creationTime: '2020-04-25T06:38:52.8233333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 72,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Sample SMS Campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-24T04:10:18.877Z',
        creationTime: '2020-04-24T04:10:18.2566667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 71,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'C2C SMS',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2020-04-17T10:59:11.16Z',
        creationTime: '2020-04-17T10:59:06.91Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 70,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Upload invoice cta campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2020-04-30T11:23:34.437Z',
        status: 'Sent',
        lastModificationTime: '2020-04-15T09:24:45.993Z',
        creationTime: '2020-04-15T09:24:36.91Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 68,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Diwali mobile campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2020-06-18T00:23:32.143Z',
        status: 'Sent',
        lastModificationTime: '2020-04-15T00:23:41.957Z',
        creationTime: '2020-04-15T00:23:41.8333333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 58,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Website analysis campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-11-20T11:41:36.41Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T09:54:27.54Z',
        creationTime: '2019-11-15T09:54:26.78Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 57,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Summer Del-Goa 10 %offer',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-11-28T00:23:07.1Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T09:34:39.537Z',
        creationTime: '2019-11-15T09:34:39.2066667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 56,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Flight Tickets',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-11-21T09:33:16.16Z',
        status: 'Sent',
        lastModificationTime: '2019-11-15T09:33:37.96Z',
        creationTime: '2019-11-15T09:33:36.6433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 55,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'test',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-08-22T12:17:58.983Z',
        creationTime: '2019-08-22T12:17:57.3966667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 54,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Flight Tickets',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-08-22T11:42:33.993Z',
        creationTime: '2019-08-22T11:42:32.33Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 53,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Upload invoice cta campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-08-01T04:46:28.99Z',
        creationTime: '2019-08-01T04:46:28.34Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 51,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Flight Tickets',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-05-27T11:50:52.623Z',
        creationTime: '2019-05-27T11:50:50.6733333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 50,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Flight Tickets',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-05-27T11:48:37.26Z',
        creationTime: '2019-05-27T11:48:34.6466667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 49,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Flight Tickets',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2019-05-27T10:21:23.813Z',
        creationTime: '2019-05-27T10:21:23.7133333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 43,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Upload invoice cta campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-05-13T06:53:50.907Z',
        status: 'Sent',
        lastModificationTime: '2019-05-13T06:53:15.38Z',
        creationTime: '2019-05-13T06:53:11.0266667Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 38,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Upload invoice cta campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: '2019-06-03T12:28:37.347Z',
        status: 'Sent',
        lastModificationTime: '2019-06-03T12:28:51.96Z',
        creationTime: '2019-05-13T06:11:30.99Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 30,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Website analysis campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2018-12-27T08:35:09.977Z',
        creationTime: '2018-12-27T08:35:09.9433333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 29,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Website analysis campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2018-12-27T08:32:38.627Z',
        creationTime: '2018-12-27T08:32:38.0033333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 24,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Website analysis campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Scheduled',
        lastModificationTime: null,
        creationTime: '2018-09-26T15:05:46.89Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      },
      {
        id: 7,
        smsCampaignId: 0,
        smsCampaign: null,
        smsName: 'Website analysis campaign',
        typeOfSms: 0,
        isScheduled: false,
        scheduledDateTimeOffset: null,
        scheduledDateTime: null,
        status: 'Sent',
        lastModificationTime: '2018-05-29T07:32:10.55Z',
        creationTime: '2018-05-29T07:32:09.7533333Z',
        isDeleted: false,
        deleterUserId: null,
        deletionTime: null,
        lastModifierUserId: null,
        creatorUserId: null
      }
    ]
  },
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
