export const UserMobileAppsMock = {
  result: [
    {
      id: 27,
      name: 'C2C',
      applicationName: null,
      osType: 1,
      description: '',
      applicationId: 'notificationc2c.notice.notificationc2c',
      senderId: '279622492011',
      deviceId: null,
      packageName: null,
      deviceStatus: false,
      organizationUnitId: 1,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2019-06-11T11:00:34.53Z',
      creatorUserId: 1
    },
    {
      id: 37,
      name: 'C2CNotify',
      applicationName: null,
      osType: 1,
      description: 'test',
      applicationId: 'AIzaSyDC2Up_jGXKebcwH6_aIip9oqEbgYIPqXQ',
      senderId: '441079242914',
      deviceId: null,
      packageName: null,
      deviceStatus: false,
      organizationUnitId: 1,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2019-06-13T09:25:32.663Z',
      creatorUserId: 1
    },
    {
      id: 40,
      name: 'normal',
      applicationName: null,
      osType: 1,
      description: 'first app',
      applicationId: '123',
      senderId: '213',
      deviceId: null,
      packageName: null,
      deviceStatus: false,
      organizationUnitId: 1,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2020-05-24T14:13:51.127Z',
      creatorUserId: 1
    },
    {
      id: 41,
      name: 'normal3',
      applicationName: null,
      osType: 1,
      description: 'first app',
      applicationId: '234',
      senderId: '32',
      deviceId: null,
      packageName: null,
      deviceStatus: false,
      organizationUnitId: 1,
      isDeleted: false,
      deleterUserId: null,
      deletionTime: null,
      lastModificationTime: null,
      lastModifierUserId: null,
      creationTime: '2020-05-24T14:14:47.533Z',
      creatorUserId: 1
    }
  ],
  targetUrl: null,
  success: true,
  error: null,
  unAuthorizedRequest: false,
  __abp: true
};
